server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**

        - id: rating-service
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

        - id: hotel-service
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**

        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**

  config:
    import: optional:configserver:http://localhost:8087

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka